### ISSUE TITLE
[CI] Add missing `title:` property in issue template

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/LinkFree-CLI#45]
### What would you like to share?

Add the missing name: `title:` property in [bug.yaml](https://github.com/Pradumnasaraf/LinkFree-CLI/blob/main/.github/ISSUE_TEMPLATE/bug.yaml) Issue template.

#### Current state:

```yaml
name: 🐛 Bug
description: Report an issue to help improve the project.
labels: ['bug']
```

#### Fix: 

```yaml
name: 🐛 Bug
description: Report an issue to help improve the project.
title: "[BUG] <description>"  # this will get added
labels: ["bug"]
```

If you have any doubts feel free to ask.
