### ISSUE TITLE
[CI] Add missing `value:` property in issue template

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/LinkFree-CLI#46]
### What would you like to share?

Add `value:` property to the `attributes:` under `id: description` in [bug.yaml](https://github.com/Pradumnasaraf/LinkFree-CLI/blob/main/.github/ISSUE_TEMPLATE/bug.yaml) Issue template.

### Changes need to add

This complete thing needs to be added

```yaml
value: |
  ###  what is the problem?
  
  ###  what is your suggested solution?
```

### After changes

The template will look like this after the addition.

```yaml
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
      value: | # This will get added
        ###  What is the problem?
        
        ###  What is your suggested solution?
    validations:
      required: true
```
